name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    env:
      IMAGE_NAME: dockerimg
      CONTAINER_NAME: MyApp

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run Unit Tests
        run: |
          python3 -m unittest -v test.py

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Stop and Remove Existing Container (if exists)
        run: |
          docker ps -q --filter "name=$CONTAINER_NAME" | grep -q . && docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME || echo "No existing container to stop."

      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 --name $CONTAINER_NAME --restart always $IMAGE_NAME

      - name: Verify Running Container
        run: |
          docker ps -a

      - name: Show Container Logs (for Debugging)
        if: always()
        run: docker logs $CONTAINER_NAME
