name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Using GitHub-hosted runner

    env:
      IMAGE_NAME: dockerimg
      CONTAINER_NAME: MyApp

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run Unit Tests
        run: |
          python3 -m unittest -v test.py

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Run Docker Container
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          docker run -d -p 80:80 --name $CONTAINER_NAME $IMAGE_NAME
